server:
  port: 8080
spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admindb
    username: myuser
    password: 123qwe

# 文档地址
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'admin'
      paths-to-match: '/**'
      #生成文档所需的扫包路径，一般为启动类目录
      packages-to-scan: com.web


#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
#  basic:
#    enable: true
#    username: admin
#    password: 123456
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: 实体类

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
# 调试生成的sql
#logging:
#  level:
#    org.mybatis: DEBUG
#    com.web.mapper: DEBUG  # 替换为你的 Mapper 包路径